# Generated by Django 4.2.2 on 2023-06-20 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Lead", "Lead"),
                            ("Member", "Member"),
                            ("Co-lead", "Co-lead"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("Bio", tinymce.models.HTMLField()),
                ("registration_no", models.CharField(blank=True, max_length=10)),
                ("codeforces_username", models.CharField(blank=True, max_length=100)),
                ("leetcode_username", models.CharField(blank=True, max_length=100)),
                ("codechef_username", models.CharField(blank=True, max_length=100)),
                ("admitted_year", models.CharField(blank=True, max_length=500)),
                ("slug", models.SlugField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
