# Generated by Django 4.2.2 on 2023-06-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cp_main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
