# Generated by Django 4.2.2 on 2023-07-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cp_main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("submitted", "submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                max_length=20,
            ),
        ),
    ]
