# Generated by Django 4.2.2 on 2023-06-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cp_main", "0002_assignment_slug_submission_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="date_assigned",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
