# Generated by Django 4.2.2 on 2023-07-04 04:31

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("cp_main", "0003_alter_assignment_date_assigned"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
