# Generated by Django 4.2.2 on 2023-06-25 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cp_main", "0003_assignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="link_to_question",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="submitted",
        ),
        migrations.CreateModel(
            name="submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(null=True, upload_to="submissions")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cp_main.assignment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignment",
            name="question",
            field=models.ManyToManyField(blank=True, to="cp_main.question"),
        ),
    ]
