# Generated by Django 4.2.2 on 2023-07-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cp_main", "0003_alter_submission_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
